CREATE TABLE IF NOT EXISTS RENTAL_LIST
(
  RENTAL_ID INT NOT NULL AUTO_INCREMENT COMMENT '대여ID',
  USER_ID INT NOT NULL COMMENT '사용자ID',
  LECTURE_ID INT NOT NULL COMMENT '강의ID',
  CHAPTER_ID INT NOT NULL COMMENT '챕터ID',
  PAY_ID INT NOT NULL COMMENT '결제내역ID',
  RENTAL_START DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '대여 시작일',
  RENTAL_END DATETIME NOT NULL COMMENT '대여 만료일',
  TARGET_DATE DATETIME COMMENT '시청 목표일',
  RENTAL_STATUS VARCHAR(30) NOT NULL DEFAULT '수강 중' COMMENT '대여 상태',
  PRIMARY KEY (RENTAL_ID),
  FOREIGN KEY(PAY_ID) REFERENCES PAY_HISTORY(PAY_ID),
  FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
  FOREIGN KEY(CHAPTER_ID) REFERENCES CHAPTER(CHAPTER_ID),
  FOREIGN KEY(LECTURE_ID) REFERENCES LECTURE(LECTURE_ID)
) COMMENT = '대여 강의 챕터 목록';