CREATE TABLE IF NOT EXISTS `LECTURE`
(
    `LECTURE_ID`    INT NOT NULL AUTO_INCREMENT COMMENT '강의ID',
    `TEACHER_ID`    INT NOT NULL COMMENT '강사ID',
    `LECTURE_TITLE` VARCHAR(255) NOT NULL COMMENT '강의명',
    `LECTURE_DESCRIPTION`    LONGTEXT NOT NULL COMMENT '강의설명',
    `LECTURE_TIME`    INT NOT NULL COMMENT '강의시간',
    `LECTURE_DIFFICULTY`    CHAR(1) NOT NULL COMMENT '난이도' CHECK(LECTURE_DIFFICULTY IN ('상', '중', '하')),
    `LECTURE_PRICE`    DECIMAL(10) NOT NULL COMMENT '강의구매가격',
    `IS_INTERESTED`    BOOLEAN DEFAULT '0' NOT NULL COMMENT '관심등록여부',
    FOREIGN KEY (`TEACHER_ID`) REFERENCES `USER`(`USER_ID`),
 	  PRIMARY KEY (`LECTURE_ID`)
) COMMENT = '강의';