CREATE TABLE IF NOT EXISTS `QUESTION_COMMENT`
(
    `COMMENT_ID`    INT NOT NULL AUTO_INCREMENT COMMENT '댓글ID',
 	  `QUESTION_ID`    INTEGER NOT NULL COMMENT '질문게시판ID',
    `USER_ID`    INT NOT NULL COMMENT '사용자ID',
    `USER_NICKNAME` VARCHAR(30) NULL COMMENT '사용자닉네임',
    `COMMENT_CONTENT`    VARCHAR(255) NOT NULL COMMENT '댓글내용',
    `COMMENT_TIME`    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '작성시간',
    `IS_DELETED`	BOOLEAN DEFAULT 0 NOT NULL COMMENT '댓글삭제여부',
 PRIMARY KEY ( `COMMENT_ID` ),
 FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
 FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTION_POST`(`QUESTION_ID`)
) COMMENT = '댓글';