CREATE TABLE `STUDY_GROUP` (
    `STUDY_GRP_ID` INT NOT NULL AUTO_INCREMENT COMMENT '스터디그룹ID',
    `STUDY_GRP_LEADER_ID` INT NOT NULL COMMENT '사용자ID',
    `STUDY_GRP_TITLE` VARCHAR(255) NOT NULL COMMENT '스터디그룹제목',
    `STUDY_GRP_CONTENT` VARCHAR(255) NOT NULL COMMENT '스터디그룹내용',
    `STUDY_GRP_STATUS` BOOLEAN DEFAULT '1' NOT NULL COMMENT '스터디그룹모집현황',
    `STUDY_GRP_MAX_MEMBER` INT DEFAULT 10 NOT NULL COMMENT '스터디그룹최대인원',
    `STUDY_GRP_LINK` VARCHAR(255) NOT NULL COMMENT '스터디그룹링크',
    `STUDY_GRP_END_STATUS` TINYINT(1) DEFAULT 0 NOT NULL COMMENT '스터디그룹종료상태 (1: 종료, 0: 진행중)',
    `CURRENT_MEMBER_COUNT` INT DEFAULT 1 NOT NULL COMMENT '현재멤버수',
    PRIMARY KEY (`STUDY_GRP_ID`),
    FOREIGN KEY (`STUDY_GRP_LEADER_ID`) REFERENCES `USER` (`USER_ID`)
) COMMENT = '스터디그룹';