CREATE TABLE IF NOT EXISTS `NOTIFICATION`
(
    `NOTIF_ID`    INT NOT NULL AUTO_INCREMENT COMMENT '알림ID',
    `USER_ID`    INT NOT NULL COMMENT '사용자ID',
    `NOTIF_TYPE`    CHAR NOT NULL COMMENT '알림타입',
    CHECK(NOTIF_TYPE IN ('N', 'W', 'C', 'Q')),
    `IS_READ`    BOOLEAN DEFAULT '0'  NOT NULL COMMENT '알림상태',
    `NOTIF_CONTENT`    LONGTEXT NOT NULL COMMENT '알림내용',
    PRIMARY KEY (`NOTIF_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) COMMENT = '알림';