CREATE TABLE `STUDY_GROUP_APPLICATION` (
    `STUDY_GRP_APPLICATION_ID` INT NOT NULL AUTO_INCREMENT COMMENT '신청ID',
    `STUDY_GRP_ID` INT NOT NULL COMMENT '스터디그룹ID',
    `USER_ID` INT NOT NULL COMMENT '사용자ID',
    `STATUS` TINYINT(1) DEFAULT 0 NOT NULL COMMENT '신청 상태 (0: 대기중, 1: 승인됨, 2: 거절됨)',
    PRIMARY KEY (`STUDY_GRP_APPLICATION_ID`),
    FOREIGN KEY (`STUDY_GRP_ID`) REFERENCES `STUDY_GROUP` (`STUDY_GRP_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) COMMENT = '스터디그룹 신청 테이블';