CREATE TABLE IF NOT EXISTS CHAPTER
(
  CHAPTER_ID INT NOT NULL AUTO_INCREMENT COMMENT '챕터ID',
  LECTURE_ID INT NOT NULL COMMENT '강의ID',
  CHAPTER_NUMBER INT NOT NULL COMMENT '챕터번호',
  CHAPTER_TITLE VARCHAR(255) NOT NULL COMMENT '챕터명',
  CHAPTER_TIME INT NOT NULL COMMENT '챕터시간',
  REFERENCE_PATH VARCHAR(255) NOT NULL COMMENT '참조경로',
  PRIMARY KEY (CHAPTER_ID),
  FOREIGN KEY (LECTURE_ID) REFERENCES `LECTURE`(LECTURE_ID)
) COMMENT = '강의별챕터';