CREATE TABLE IF NOT EXISTS RENTAL_PRICE_TBL
(
  RENTAL_PRICE_ID INT NOT NULL AUTO_INCREMENT COMMENT '대여가격ID',
  RENTAL_DAY INT NOT NULL COMMENT '대여기간',
  RENTAL_PRICE DECIMAL(10) NOT NULL COMMENT '대여가격',
  PRIMARY KEY (RENTAL_PRICE_ID)
) COMMENT = '대여가격';