CREATE TABLE IF NOT EXISTS `CHAPTER_PRICE`
(
    `CHAPTER_PRICE_ID`    INT NOT NULL AUTO_INCREMENT COMMENT '챕터별가격ID',
    `CHAPTER_ID`    INT NOT NULL COMMENT '챕터ID',
    `RENTAL_PRICE_ID`	INT NOT NULL COMMENT '대여가격ID',
    PRIMARY KEY (`CHAPTER_PRICE_ID`),
    FOREIGN KEY (`RENTAL_PRICE_ID`) REFERENCES `RENTAL_PRICE_TBL`(`RENTAL_PRICE_ID`),
    FOREIGN KEY (`CHAPTER_ID`) REFERENCES `CHAPTER`(CHAPTER_ID) -- 외래키 제약조건
) COMMENT = '챕터별가격';