CREATE TABLE `REVIEW_LIKE`
(
	 `REVIEW_GOOD_ID` INT NOT NULL AUTO_INCREMENT COMMENT '후기게시글좋아요ID',
    `REVIEW_ID`    INT NOT NULL COMMENT '후기게시판ID',
    `USER_ID`    INT NOT NULL COMMENT '사용자ID',
 PRIMARY KEY ( `REVIEW_GOOD_ID` ),
 FOREIGN KEY(`USER_ID`) REFERENCES `USER`(`USER_ID`),
 FOREIGN KEY(`REVIEW_ID`) REFERENCES `REVIEW_POST`(`REVIEW_ID`)
) COMMENT = '후기게시글좋아요';