CREATE TABLE `PURCHASED_LECTURE`
(
    `PURCHASED_LECTURE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '구매강의ID',
    `PAY_HISTORY_ID`       INT NOT NULL COMMENT '결제내역ID',
    `BUYER_ID`             INT NOT NULL COMMENT '구매자ID',
    `LECTURE_ID`           INT NOT NULL COMMENT '강의ID',
    PRIMARY KEY (`PURCHASED_LECTURE_ID`),
    FOREIGN KEY (`PAY_HISTORY_ID`) REFERENCES PAY_HISTORY(`PAY_ID`),
    FOREIGN KEY (`LECTURE_ID`) REFERENCES LECTURE(`LECTURE_ID`),
    FOREIGN KEY (`BUYER_ID`) REFERENCES USER(`USER_ID`)
) COMMENT = '구매강의목록';